spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    #password: Z105401461ch
    #password: 12345678
    password: Qq1234@#
    #url: jdbc:mysql://localhost:3306/engineer_db?serverTimezone=UTC&characterEncoding=utf-8
    url: jdbc:mysql://rm-2ev0f7rk83r5e5a729o.mysql.rds.aliyuncs.com:3306/engineer_db?serverTimezone=UTC&characterEncoding=utf-8
    #    type: com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource