server:
  port: 8050
  servlet:
    context-path: /assist
    session:
      timeout: 30m
spring:
  profiles:
    active: dev
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:schema-mysql.sql
      table-name: SPRING_SESSION
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isActive
      logic-not-delete-value: 1
      logic-delete-value: 0
      id-type: auto
      table-underline: true
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true

pagehelper:
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
  helper-dialect: mysql
  page-size-zero: true

custom:
  aws:
    access-key: CHOBITACCESSKEY
    secret-key: CHOBIT/THISIS006SECRET007Key/dotORG
    bucket: zhyea
    endpoint: www.zhyea.com:80

